sudo: required
dist: trusty
language: node_js
node_js:
  - "10"

before_install:
  - cd fantastic-feasts  
  - npm install

script:
  - npm run build-dev

deploy:
  provider: script
  skip-cleanup: true
  keep-history: true
  script: bash ../deploy.sh
  on:
    all_branches: true

